spring:
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8094

ribbon:
  IsSecure: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

---

spring:
  profiles: default
  jpa:
    database: HSQL

security:
  basic:
    enabled: false

---

spring:
  profiles: cloud
  jpa:
    database: HSQL
